services:
  clientemqtt:
    build: ./clienteMqtt
    image: clientemqtt
    container_name: clientemqtt
    environment:
      - TZ=America/Argentina/Buenos_Aires 
      - SERVIDOR=${SERVIDOR}
      - PUERTO=${PUERTO}
      - TOPICO_1=${TOPICO_1}
      - TOPICO_2=${TOPICO_2}
      - TOPICO_PUB=${TOPICO_PUB}
    restart: unless-stopped